sudo: required

services:
  - docker

language: generic

env:
  - DOCKER_CONTAINER=openjdk8
  - DOCKER_CONTAINER=openjdk11

script: docker-compose run --rm $DOCKER_CONTAINER bash -c "./config/ci/install-schemas.sh && ./gradlew test"
