kind: PersistentVolume
apiVersion: v1
metadata:
  name: divolte
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/divolte/

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: divolte
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
